### ISSUE TITLE
close 1006 

### ISSUE THREAD

**Issue by foundVanting** [nshafer/phx#2] opened 2022-05-27 08:43 UTC
hi, thank you provide the package.
when i run A few hours ,it break.
What should I do? Thank you for your advice。
it`s logs :
``` 
[ERROR] <socket> Read error: websocket: close 1006 (abnormal closure): unexpected EOF
[ERROR] <channel> Channel 'collection:xxx' error: <nil>
[ERROR] <socket> Connection error: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.112.2.55:33740->104.18.0.63:443: write: broken pipe
[ERROR] <channel> Channel 'collection:xxx' error: <nil>
[INFO] <socket> Disconnected from wss://stream.openseabeta.com/socket?token=xxx
[INFO] <socket> Connected to wss://stream.openseabeta.com/socket?token=xxxx
[INFO] <channel> attempting to rejoin channel
[INFO] <channel> joined channel 'collection:xxx' joinRef:666
Joined channel: collection:XXX map[]
```

**Comment by nshafer** [comment] 2022-05-27 16:13
I have no idea... it looks like either the server or something between the client is closing the connection. The good news is that the phx library is detecting it and reconnecting like it should. I'm just now starting the use the library myself in the real world in the project I wrote it for, so as I do that I will probably discover things here and there that need to be adjusted for. And it's far from a 1.0 release... it's basically just written to spec and not battle tested yet. For this particular case, if I could reproduce it, I would probably start capturing packets and see if I can see what's going on at the network layer. LMK if you find anything else out.

**Comment by benleb** [comment] 2022-06-04 14:02
@foundVanting could you maybe share the code how you got to this point? :D me and some other people from https://github.com/ProjectOpenSea/stream-js/issues/122 could be interested and then could join to debug & solve issues like this one here :D

**Comment by nshafer** [comment] 2022-06-04 22:48
I provided a couple simple examples in https://github.com/nshafer/phx/blob/main/examples/simple/simple.go and https://github.com/nshafer/phx/blob/main/examples/cli/cli.go. It looks like stream-js just uses the official phoenix JS library, which I copied pretty closely for this module, so you would probably just need to port/copy the code from https://github.com/ProjectOpenSea/stream-js/blob/main/src/client.ts specifically where it connects to the Socket then joins a channel with the topic `collection:<slug>`.

**Closed as completed by nshafer** 2022-06-04 22:48 UTC

**Comment by foundVanting** [comment] 2022-06-09 08:55
> @foundVanting could you maybe share the code how you got to this point? :D me and some other people from [ProjectOpenSea/stream-js#122](https://github.com/ProjectOpenSea/stream-js/issues/122) could be interested and then could join to debug & solve issues like this one here :D

https://github.com/foundVanting/opensea-stream-go

**Comment by foundVanting** [comment] 2022-06-09 08:56
@benleb  https://github.com/foundVanting/opensea-stream-go

**Comment by foundVanting** [comment] 2022-09-13 10:08
@nshafer hello,i use https://github.com/foundVanting/opensea-stream-go listen listing cancel,
 it unable to receive data when more than 24h, the log show attempting to rejoin channel。
but i use  https://github.com/ProjectOpenSea/stream-js ,it is work after 24h。

**Comment by ai-chen2050** [comment] 2022-12-05 14:44
> @nshafer hello,i use https://github.com/foundVanting/opensea-stream-go listen listing cancel, it unable to receive data when more than 24h, the log show attempting to rejoin channel。 but i use https://github.com/ProjectOpenSea/stream-js ,it is work after 24h。

@foundVanting Hello, had been solved this problem? I meets the phenomenon when using your package  https://github.com/foundVanting/opensea-stream-go. soldevent and listing cancel as the same issue.
